### ISSUE TITLE
REVIEW Week 7

### ISSUE THREAD

**Issue by chinyakao** [SOA-idk/NoFB#7]
1. `Rakefile`  line 4 `puts 'rake -T'` should be like `` puts `rake -T` ``. Notice that the quotation marks should be the one next to the `keyboard number 1` not the one next to the `keyboard enter`.
When you run the `rake` in the console, it will show all the rakefile commands instead of 'rake -T'.
2. There are 5 errors from 7 test. Please modify your spec files. 
3. Not sure this file path `NoFB/spec/spec/fixtures/cassettes/` doing.
4. There is no `.reek.yml` file. Do you have some concern?

**Comment by chinyakao** [comment]
@hhorace @ginagigo123 @lauralishishihoohoo

**Comment by ginagigo123** [comment]
> 1. `Rakefile`  line 4 `puts 'rake -T'` should be like `` puts `rake -T` ``. Notice that the quotation marks should be the one next to the `keyboard number 1` not the one next to the `keyboard enter`.
>    When you run the `rake` in the console, it will show all the rakefile commands instead of 'rake -T'.
> 2. There are 5 errors from 7 test. Please modify your spec files.
> 3. Not sure this file path `NoFB/spec/spec/fixtures/cassettes/` doing.
> 4. There is no `.reek.yml` file. Do you have some concern?

1. We will correct this in the next version.
2. We have solved the spec errors at the #9 .
3. Sorry for forgetting to delete the wrong file.
4. Professor uses the `.reek.yml` file in order to ignore some warnings on specific files. Instead, we ignore specific functions by adding comments just above functions.
